name: Build EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: |
        g++ -static -static-libgcc -static-libstdc++ manualmapdetector.cpp -o manualmapdetector.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: manualmapdetector
        path: manualmapdetector.exe
